name: k_chart_multiple
description: A Flutter K Chart support multiple secondary chart.
version: 1.0.0
homepage: https://github.com/Aressssssssssssss/k_chart_multiple

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: